forecast/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout

app_name = 'forecast'
urlpatterns = [
    url(r'^login/$', login, {'template_name': 'forecast/login.html'}, name='login'),
    url(r'^home/$', logout, {'template_name': 'forecast/home.html'}, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.profile, name='profilepage'),
    url(r'^profile/ajax/get_graph_data/$', views.get_graph_data, name='get_graph_data'),
    url(r'^weather_records/$', views.weather_list),
]

myproject/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from myproject import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^forecast/', include('forecast.urls')),
    url(r'^$', views.home, name='home'),
    url(r'^forecast/$', views.home, name='home'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forecast/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class userprofile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_email = models.EmailField(max_length=100, default='')


class wheather(models.Model):
    created_datetime = models.DateTimeField('created date of record')
    weather_date = models.CharField(max_length=10, primary_key=True)
    min_temp = models.IntegerField(default=0)
    max_temp = models.IntegerField(default=0)
    wind = models.IntegerField(default=0)
    rain = models.CharField(max_length=10)


def save_weather_record(data):
    record = wheather(created_datetime=timezone.now(), weather_date=data['weather_Date'], min_temp=data['min_temp'],
                      wind=data['wind'], max_temp=data['max_temp'], rain=data['rain'])
    record.save()


def get_weather_records(offset=None):
    results = wheather.objects.order_by('created_datetime').all()[:10]
    data = [[item.weather_date, item.min_temp, item.max_temp, item.wind, item.rain] for item in results]
    return data

forecast/forms.py
import re
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UniqueEmailField(forms.EmailField):
    """
        * An EmailField which is valid if no User has that email.
    """

    def validate(self, value):
        super(forms.EmailField, self).validate(value)
        try:
            User.objects.get(email=value)
            raise forms.ValidationError("Email already exists")
        except User.MultipleObjectsReturned:
            raise forms.ValidationError("Email already exists")
        except User.DoesNotExist:
            pass


class ExtendedUserCreationForm(UserCreationForm):
    """
        * extends the UserCreationForm

        * Adds an email field, which uses the custom UniqueEmailField,
          Nothing will be committed if the user exists.

        * the username is the email
    """
    username = forms.CharField(required=False, max_length=30)
    email = UniqueEmailField(required=True, label='Email address')

    def __init__(self, *args, **kwargs):
        """
            * Changes the order of fields, and removes the username field.
        """
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['email', 'password1', 'password2']

    def clean(self, *args, **kwargs):
        """
            * user cleanup
            * setting username = email
        """
        cleaned_data = super(UserCreationForm, self).clean(*args, **kwargs)
        if cleaned_data.get('email', ''):
            cleaned_data['username'] = cleaned_data['email']
        return cleaned_data

    def save(self, commit=True):
        """
            * Saves the email after the normal save is complete.
        """
        user = super(UserCreationForm, self).save(commit)
        if user:
            user.email = self.cleaned_data['email']
            user.set_password(self.cleaned_data['password1'])
            if commit:
                user.save()
        return user

forecast/views.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from forecast.models import wheather
from forecast.serializers import wheatherSerializer
from forecast.forms import ExtendedUserCreationForm


def register(request):
    if request.method == 'POST':
        form = ExtendedUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('../profile')
        else:
            error = str(form.errors)
            form = ExtendedUserCreationForm()
            args = {'form': form, 'error': error}
            return render(request, 'forecast/reg_form.html', args)
    else:
        form = ExtendedUserCreationForm()
        args = {'form': form, 'error': ''}
        return render(request, 'forecast/reg_form.html', args)


def profile(request):
    args = {'user': request.user}
    return render(request, 'forecast/profile.html', args)


@csrf_exempt
def get_graph_data(request):
    from django.http import JsonResponse
    from forecast.models import get_weather_records

    data = get_weather_records(offset=None)

    data = {
        'json_data': data
    }
    return JsonResponse(data)


@csrf_exempt
def weather_list(request):
    """
        List all weather records.
    """
    # TODO, Validate that only logged in users get to
    if request.method == 'GET':
        weather_obj = wheather.objects.all()
        serializer = wheatherSerializer(weather_obj, many=True)
        return JsonResponse(serializer.data, safe=False)
    else:
        return JsonResponse('no other requests allowed', status=400)

myproject/views.py
from django.shortcuts import redirect


def home(request):
    return redirect('/forecast/home')

forecast/templates/base.html
<html>
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'forecast/css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% load static %}
    <link rel="shortcut icon" type="image/ico" href="{% static 'forecast/media/favicon.ico' %}">

    {% block head %}
    <meta charset="UTF-8">
    <title>Forecast</title>

    {% endblock %}
  </head>

  <body>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block nav %}
      <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-end fixed-top">

        <a class="navbar-brand" href="{% url 'forecast:home' %}">Home</a>
        {% load static %}

        <div class="collapse navbar-collapse flex-grow-0 ml-auto" id="navbarSupportedContent">
            <ul class="navbar-nav text-right">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'forecast:login' %}">Login</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'forecast:register' %}">Sign Up</a>
                </li>
            </ul>
        </div>
      </nav>
    {% endblock %}

    <div id="page-container">
      <div id="page-main">
        {% block body %}
        {% endblock %}
      </div>
    </div>

    <footer id="footer">
      <hr>
      <center>
          <ul class="list-inline">
            <li><a href="https://github.com/zak-ken/django-forecast">Fork This On GitHub</a></li>
          </ul>
      </center>
    </footer>

  </body>
</html>

forecast/templates/forecast/home.html
{% extends 'base.html' %}
{% block body %}


<div id="WeatherCarousel" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#WeatherCarousel" data-slide-to="0"></li>
    <li data-target="#WeatherCarousel" data-slide-to="1"></li>
    <li data-target="#WeatherCarousel" data-slide-to="2" class="active"></li>
    <li data-target="#WeatherCarousel" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item" data-interval="5000">
      {% load static %}
      <img src="{% static 'forecast/media/carousel/winter.jpg' %}" class="d-block w-100" alt="winter-image">
      <div class="carousel-caption d-none d-md-block">
        <p><a class="btn btn-lg btn-primary winter-outline" href="#Winter" role="button">Winter Info.</a></p>
      </div>
    </div>
    <div class="carousel-item" data-interval="5000">
      {% load static %}
      <img src="{% static 'forecast/media/carousel/autumn.jpg' %}" class="d-block w-100" alt="autumn-image">
      <div class="carousel-caption d-none d-md-block">
        <p><a class="btn btn-lg btn-primary autumn-outline" href="#Autumn" role="button">Autumn Info.</a></p>
      </div>
    </div>
    <div class="carousel-item active" data-interval="5000">
      {% load static %}
      <img src="{% static 'forecast/media/carousel/summer.jpg' %}" class="d-block w-100" alt="summer-image">
      <div class="carousel-caption d-none d-md-block">
        <p><a class="btn btn-lg btn-primary summer-outline" href="#Summer" role="button">Summer Info.</a></p>
      </div>
    </div>
    <div class="carousel-item" data-interval="5000">
      {% load static %}
      <img src="{% static 'forecast/media/carousel/spring.jpg' %}" class="d-block w-100" alt="spring-image">
      <div class="carousel-caption d-none d-md-block">
        <p><a class="btn btn-lg btn-primary spring-outline" href="#Spring" role="button">Spring Info.</a></p>
      </div>
    </div>
  </div>
</div>

<br>

<div class="container marketing">
  <hr class="featurette-divider">

  <div class="row featurette" id="Autumn">
    <div class="col-md-7">
      <h2 class="featurette-heading">Autumn</h2>
      <p class="lead">In autumn, or fall, temperatures start to drop resulting in plants growing dormant. Some animals start to prepare themselves for the winter that lies ahead by storing food and traveling to warmer areas. Many cultures celebrate the season due the harvests that they receive, for instance Thanksgiving for example is a historical commemoration but there is actually a link between this and the season, giving praise to what was given.</p>
    </div>
    <div class="col-md-5 head-line">
      {% load static %}
      <img src="{% static 'forecast/media/headline/autumn.jpg' %}" alt="Autumn" class="rounded">
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette" id="Winter">
    <div class="col-md-7 order-md-2">
      <h2 class="featurette-heading">winter</h2>
      <p class="lead">Winter is coming! we’ll know when the white walkers are at walls when we feel the cold chill that winter brings. In Winter animals find ways to warm themselves, some even change their appearance to adapt or go into slumber for very long periods as a way to preserve energy, such as bears. In a similar theme to the autumn celebration, Winter Festivals is often celebrated as the return of light, this is due to the fact that during winter there are longer nights and shorter days. For instace the Indian festival of Diwali, between October and November celebrates the triumph of righteousness, and of light over darkness.</p>
    </div>
    <div class="col-md-5 order-md-1 head-line">
      {% load static %}
      <img src="{% static 'forecast/media/headline/winter.jpg' %}" alt="Winter" class="rounded">
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette" id="Spring">
    <div class="col-md-7">
      <h2 class="featurette-heading">Spring</h2>
      <p class="lead">In spring the seeds take root and vegetation begins to blossom. The weather is warmer resulting in animals waking or return from warmer climates, often with young offspring. The increased rainfall as well as the melting snow from the previous season provides the chance of flooding in water ways.</p>
    </div>
    <div class="col-md-5 head-line">
      {% load static %}
      <img src="{% static 'forecast/media/headline/spring.jpg' %}" alt="Spring" class="rounded">
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette" id="Summer">
    <div class="col-md-7 order-md-2">
      <h2 class="featurette-heading">Summer</h2>
      <p class="lead">In summer temperatures start to increase and rise to the hottest of the year. Often times droughts and heat waves occur  if the temp spikes too high, causing danger to people, animals and plants. One such scenario for example in  summer of 2003, the  extreme temperatures claimed more than 30,000 lives, according to Encyclopedia Britannica. Forest fires may become more frequent while rainfall may increase in some areas, as well.</p>
    </div>
    <div class="col-md-5 order-md-1 head-line">
      {% load static %}
      <img src="{% static 'forecast/media/headline/summer.jpg' %}" alt="Summer" class="rounded">
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="container">
    <div class="col">
      <h2>Login to view the current weather in your area.</h2>
      <p>Or do a search on this <a href="#">page</a> to view your current weather conditions.</p>
    </div>
  </div>
</div>
{% endblock %}

forecast/templates/forecast/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>welcome</h1>
    <p>
        You can login here
    </p>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>

</div>
{% endblock %}

forecast/templates/forecast/profile.html
{% extends 'base.html' %}
{% csrf_token %}
{% block head %}
<title>Profile</title>
{% endblock %}

{% block nav %}
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-end fixed-top">
      <a class="navbar-brand" href="{% url 'forecast:home' %}">Home</a>

      <div class="collapse navbar-collapse flex-grow-0 ml-auto" id="navbarSupportedContent">
          <ul class="navbar-nav text-right">
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'forecast:home' %}">Logout</a>
              </li>
          </ul>
      </div>
    </nav>
{% endblock %}

{% block body %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
{% load static %}
<script type="text/javascript" src="{% static 'forecast/js/weather.js' %} "></script>

<div class="container">
    <div id="Data_Table_Cont">
    </div>
</div>
{% endblock %}

forecast/templates/forecast/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Registration Form</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ error }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}